### ISSUE TITLE
Scheduled tasks/cron?

### ISSUE THREAD

**Issue by sudofox** [CommandString/DiscordPHP-Design-Structure#6]
This framework looks pretty neat. I'm thinking about trying it out, but what would make it perfect is having a way to schedule tasks or schedule repeating tasks (essentially, like `atd` and `crond` can handle.) Would be able to persist scheduled tasks thru a restart too.

This could make it possible to automatically do things like schedule deletion of a particular message (like an auto-deleted bot response that goes away after a while to cut down spam), checking if user roles need to be updated, sending certain daily or weekly messages, etc.

**Comment by CommandString** [comment]
[ReactPHP Periodic Timer](https://reactphp.org/event-loop/#addperiodictimer) probably is what you're looking for. Additionally, if you want to speak more about this you can add me on Discord, Command_String#8821, or join my [discord server](https://discord.gg/TgrcSkuDtQ) as I'll respond quicker there
